// <auto-generated />
using BackEndApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEndApp.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20180814005447_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEndApp.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionAr");

                    b.Property<string>("DescriptionEn");

                    b.Property<string>("NameAr");

                    b.Property<string>("NameEn");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new { DepartmentId = 1, DescriptionAr = "وصف القسم الأول", DescriptionEn = "First Department Desc", NameAr = "القسم الأول", NameEn = "First Dept" },
                        new { DepartmentId = 2, DescriptionAr = "وصف القسم الثاني", DescriptionEn = "Second Department Desc", NameAr = "القسم الثاني", NameEn = "Second Dept" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
